version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
      - REPOSITORY_URI=xxxxxxxxxx.dkr.ecr.us-west-2.amazonaws.com/yyyyyy
      - IMAGE_TAG=build-$(echo ${CODEBUILD_BUILD_ID} | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - docker --version
      - echo Building the Docker image...
      - docker build -t ${REPOSITORY_URI}:latest .
      - docker tag ${REPOSITORY_URI}:latest ${REPOSITORY_URI}:${IMAGE_TAG}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push ${REPOSITORY_URI}:latest
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - printf '[{"name":"app-image","imageUri":"%s"}]' ${REPOSITORY_URI}:${IMAGE_TAG} > imageDetail.json
artifacts:
  files:
    - imageDetail.json
